# engines:
#   eslint:
#     enabled: true
#     channel: "eslint-2"
#   duplication:
#     enabled: true
#     checks:
#       Similar code:
#         enabled: false
#       Identical code:
#         enabled: false
#     config:
#       languages:
#       - javascript
# ratings:
#   paths:
#   - src/*.js
# exclude_paths:
# - 'jasmine/*'

# engines:
#   eslint:
#     enabled: true
#   duplication:
#     enabled: false
#     config:
#       languages:
#       - javascript
# ratings:
#   paths:
#   - "**.js"
# exclude_paths:
# - 'jasmine/*'

engines:
  eslint:
    enabled: true
    channel: "eslint-2"
  duplication:
    enabled: false
    checks:
      Similar code:
        enabled: false
    config:
      languages:
      - javascript
ratings:
  paths:
  - src/*.js
exclude_paths:
- jasmine/lib/jasmine-2.3.4/jasmine-html.js
- jasmine/lib/jasmine-2.3.4/jasmine.js
- gulpfile.js

